name: Set elevator to unusable
on:
  issues:
    types: [opened]

jobs:
  build:
    name: Elevator to unusable
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup git config
        run: |
          # setup the username and email
          git config user.name "Zenika Nantes Elevator bot"
          git config user.email "<>"
      
      - name: Update elevator state
        run: |
          sed -i 's/Oui/Non/' index.html
          git add .
          git commit -m "set elevator to unusable"
          git push origin main
